background_opacity 1
dynamic_background_opacity no
#background_blur 24

foreground #b8b8c8
background #05050a
cursor #c8c8e0
selection_foreground #05050a
selection_background #505068

color0 #0e0e16
color8 #242430

color1 #786878
color9 #907888

color2 #607060
color10 #788878

color3 #888070
color11 #a09880

color4 #506080
color12 #6878a0

color5 #706880
color13 #888098

color6 #506870
color14 #688890

color7 #a0a0b0
color15 #c8c8d8

font_family JetBrains Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0

window_padding_width 14
window_padding_height 14

cursor_shape underline
force_cursor yes
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

inactive_border_color #12121a
active_border_color #303048

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 2
active_tab_foreground #c8c8e0
active_tab_background #141420
active_tab_font_style bold
inactive_tab_foreground #303040
inactive_tab_background #0a0a12
inactive_tab_font_style normal
tab_bar_background #06060c
tab_title_template " {title} "

allow_remote_control yes
listen_on unix:/tmp/kitty
mouse_hide_wait 2.0
enable_audio_bell no
update_check_interval 0
close_on_child_death no
inactive_text_alpha 0.35
