$mod = SUPER

# logout
bind = $mod + CTRL, ESCAPE, exec, wayland-logout

# mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

## mouselock (toggle mod)

bind = $mod, L, exec, ./.local/bin/toggle-cursor-lock.sh

# fj
bind = CTRL + ALT, T, exec, kitty
bind = CTRL + ALT, F, exec, thunar
bind = $mod, SPACE, exec, hyprctl switchxkblayout current next

bind = $mod, D, exec, rofi -show drun
bind = $mod, Q, killactive
bind = $mod, M, exit

# Screenshooter
bind = CTRL SHIFT, Print, exec, grim ~/Pictures/screenshot-$(date +%s).png
bind = , Print, exec, grim - | wl-copy
bind = SHIFT, Print, exec, bash -c 'region=$(slurp) && sleep 0.3 && grim -g "$region" - | wl-copy'

# window focus
bind = ALT, TAB, cyclenext
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
bind = $mod, C, centerwindow

# workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9

## special workspaces
bind = $mod, S, togglespecialworkspace, magic
bind = $mod SHIFT, S, movetoworkspace, special:magic

## switch workspace with MWHEELUP/MWHEELDOWN
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

## move window to workspace
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9

# toggle floating bind for window rules
bind = $mod, T, togglefloating
