# off blur for better optimizations = waybar / swaync
layerrule = blur off, match:namespace waybar
layerrule = blur off, match:namespace swaync-notification-window
layerrule = blur off, match:namespace swaync-control-center

# rofi layerrules
layerrule = blur yes, match:namespace rofi
layerrule = ignore_alpha 0.4, match:namespace rofi
layerrule = no_anim on, match:namespace rofi