animations {
	enabled = yes

    bezier = emerge, 0.16, 1.0,  0.3,  1.0
    bezier = vanish, 0.33, 1.0,  0.68, 1.0
    bezier = drift, 0.25, 0.46, 0.45, 1.0
    bezier = snap, 0.12, 1.0,  0.2,  1.0
    bezier = linear, 0.0,  0.0,  1.0,  1.0

    animation = windowsIn, 1, 5, emerge, slidefadevert 8%
    animation = windowsOut, 1, 4, vanish, slidefadevert 8%
    animation = windowsMove, 1, 5, drift
    animation = fadeIn, 1, 5, emerge
    animation = fadeOut, 1, 4, vanish
    animation = fadeDim, 1, 3, snap
    animation = fadeShadow, 1, 5, emerge
    animation = fadeLayers, 1, 4, vanish

    animation = border, 1, 3, snap
    animation = borderangle, 1, 180, linear, loop

    animation = workspaces, 1, 7, emerge, slidevert
    animation = specialWorkspace, 1, 6, vanish, slidevert

    animation = layers, 1, 4, vanish, fade
}